import * as React from 'react';
import { ChatMessage, ChatMessageRole } from '../types';
import { UserIcon, AIIcon } from './icons/Icons';
import SourceLinks from './SourceLinks';

interface MessageProps {
  message: ChatMessage;
}

const Message: React.FC<MessageProps> = ({ message }) => {
  const isUser = message.role === ChatMessageRole.USER;
  const isImage = !isUser && message.content.startsWith('data:image');

  const messageContainerClasses = `flex items-start gap-3 ${
    isUser ? 'justify-end' : ''
  }`;
  
  const messageBubbleClasses = `px-4 py-3 rounded-2xl max-w-sm md:max-w-md lg:max-w-lg break-words ${
    isUser
      ? 'bg-red-600 text-white rounded-br-none'
      : 'bg-white text-slate-800 rounded-bl-none border border-slate-200'
  }`;

  const imageBubbleClasses = `rounded-2xl max-w-sm md:max-w-md lg:max-w-lg overflow-hidden bg-white rounded-bl-none border border-slate-200`;

  const linkify = (text: string) => {
    const urlRegex = /(https?:\/\/[^\s]+)/g;
    return text.split(urlRegex).map((part, i) => {
      if (part.match(urlRegex)) {
        return (
          <a
            key={i}
            href={part}
            target="_blank"
            rel="noopener noreferrer"
            className="text-red-500 hover:underline"
          >
            {part}
          </a>
        );
      }
      return part;
    });
  };

  const renderContent = () => {
    if (isImage) {
      return (
        <div className={imageBubbleClasses}>
          <img src={message.content} alt="Generated by AI" className="w-full h-auto" />
        </div>
      );
    }
    // Don't render an empty bubble if user only sent an attachment
    if (isUser && !message.content.trim()) {
        return null;
    }
    return (
      <div className={messageBubbleClasses}>
        <p className="whitespace-pre-wrap">{linkify(message.content)}</p>
        {!isUser && message.modelSources && message.modelSources.length > 0 && (
            <p className="mt-3 pt-2 border-t border-slate-200/60 text-xs text-slate-500">
                Researched using: {message.modelSources.join(', ')}
            </p>
        )}
      </div>
    );
  };
  
  const bubbleWrapperClasses = `flex flex-col gap-2 ${isUser ? 'items-end' : 'items-start'}`;

  return (
    <div className={messageContainerClasses}>
      {!isUser && (
        <div className="w-8 h-8 flex-shrink-0 bg-slate-200 rounded-full flex items-center justify-center">
          <AIIcon className="w-5 h-5 text-slate-600" />
        </div>
      )}
      <div className={bubbleWrapperClasses}>
        {message.attachment && isUser && (
            <div className="max-w-xs md:max-w-sm overflow-hidden rounded-2xl rounded-br-none">
              <img src={message.attachment.url} alt="User upload" className="w-full h-auto" />
            </div>
        )}
        {renderContent()}
        {!isUser && <SourceLinks sources={message.sources || []} />}
      </div>
      {isUser && (
         <div className="w-8 h-8 flex-shrink-0 bg-red-500 rounded-full flex items-center justify-center">
          <UserIcon className="w-5 h-5 text-white" />
        </div>
      )}
    </div>
  );
};

export default Message;
